import Head from 'next/head'
import Link from 'next/link'
import React, { useState } from 'react'
import Navbar from '../../components/Layout/Navbar'
import ProductTable from '../../components/Tables/ProductTable'
import { getProducts } from '../../services/lib/productHandler'

const Products = ({ products }) => {

    const [productState, setProductState] = useState(products);

    return (
        <div className="min-h-screen w-full">
            <Head>
                <title>addidas Official Website India</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <Navbar />

            <main className="flex flex-col justify-center items-center mt-32">

                <div className='w-10/12'>
                    <h1 className='font-bold text-3xl'>Hello there, mukulrajpoot@gmail.com</h1>
                    <p className='mb-4'>Here is some information about products</p>

                    <div className='flex justify-between items-center'>
                        <h1 className='font-bold text-xl my-4'>Products</h1>
                        <Link href="/products/add" passHref>
                            <button className='bg-black p-3 px-6 text-white uppercase font-bold'>Add Product</button>
                        </Link>
                    </div>

                    <ProductTable products={productState} setProductState={setProductState} />
                </div>
            </main>
        </div>
    )
}

export default Products

export async function getServerSideProps() {

    let products;

    try {
        const res = await getProducts();
        if (res.data.success) {
            products = res.data.products;
        } else {
            products = [];
        }
    } catch (err) {
        console.log(err.message)
    }

    return {
        props: { products }
    }
}