import Head from 'next/head'
import Link from 'next/link'
import React, { useState } from 'react'
import Header from '../../components/common/Header'
import Navbar from '../../components/Layout/Navbar'
import ProductTable from '../../components/Tables/ProductTable'
import { getAllProducts } from '../../services/api'

const Products = ({ products }) => {

    const [productState, setProductState] = useState(products);

    return (
        <div className="min-h-screen w-full">
            <Head>
                <title>addidas Official Website India</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <Navbar />

            <main className="flex flex-col justify-center items-center mt-32">

                <div className='w-10/12'>

                    <Header />

                    <div className='flex justify-between items-center'>
                        <h1 className='font-bold text-xl my-4'>Products</h1>
                        <Link href="/products/add" passHref>
                            <button className='bg-black p-3 px-6 text-white uppercase font-bold'>Add Product</button>
                        </Link>
                    </div>

                    <ProductTable products={productState} setProductState={setProductState} />
                </div>
            </main>
        </div>
    )
}

export default Products

export async function getStaticProps() {

    try {
        const res = await getAllProducts();

        return {
            props: { products: res.data.products },
            revalidate: 10
        }
    } catch (err) {
        console.log(err)

        return {
            props: { products: [] }
        }
    }
}