import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Header from '../../components/Layout/Header';
import Navbar from '../../components/Layout/Navbar';
import { getOrderDetail } from '../../services/lib/orderHandler';

const OrderDetails = ({ order }) => {

    const router = useRouter()

    let wn = {};

    order = order && wn

    return <div className="min-h-screen w-full">
        <Head>
            <title>addidas Official Website India</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.svg" />
        </Head>

        <Navbar />

        <main className="flex flex-col justify-center items-center mt-32">

            <div className='w-10/12'>
                <Header />
                {
                    order ? <>
                        <div className='flex justify-between items-center'>
                            <div>
                                <h1 className='font-bold text-xl mt-4'>Order Number: {order._id}</h1>
                                <h1 className='text-sm'>{order.createdAt.split("T")[0]}</h1>
                            </div>
                            <div className='gap-3 flex'>
                                <button className='border-red-800 border-2 bg-red-100 text-red-800 font-bold p-3'>Cancel Order</button>
                                <button className='border-yellow-600 border-2 bg-yellow-100 text-yellow-600 font-bold p-3'>Return/Replace</button>
                            </div>
                        </div>
                        <div className='flex'>
                            <div className='w-9/12  p-4'>

                            </div>

                            <div className='w-3/12 p-4'>
                                <h1 className='font-bold text-xl my-4'>Customer</h1>
                                <div className='border-2 border-black h-750 p-4 overflow-scroll'>
                                    <h1></h1>
                                </div>
                            </div>

                        </div>
                    </> : "No Orders Found..."
                }

            </div>
        </main>
    </div>
};

export default OrderDetails;

export async function getServerSideProps({ query }) {

    let order = null;

    try {
        const res = await getOrderDetail(query.order)
        order = res.data.order
    } catch (err) {
        console.log(err.response.data)
    }

    return {
        props: { order }
    }
}