import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import Header from '../../components/Layout/Header'
import Navbar from '../../components/Layout/Navbar'
import OrderTable from '../../components/Tables/OrderTable'
import { GetAllOrders } from '../../services/api'

const Order = () => {
    const [orderState, setOrderState] = useState()

    useEffect(() => {
        const fetchData = async () => {

            try {
                const res = await GetAllOrders()
                setOrderState(res.data.orders)
                console.log(res.data)
            } catch (err) {
                console.log(err)
            }
        }

        fetchData()
    }, [])

    return (
        <div className="min-h-screen w-full">
            <Head>
                <title>addidas Official Website India</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <Navbar />

            <main className="flex flex-col justify-center items-center mt-32">
                <div className='w-10/12'>
                    <Header />

                    <h1 className='font-bold text-xl my-4'>Orders</h1>

                    <OrderTable orders={orderState} setOrderState={setOrderState}
                    />
                </div>
            </main>
        </div>
    )
}

export default Order