import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import Header from '../../components/Layout/Header'
import Navbar from '../../components/Layout/Navbar'
import OrderTable from '../../components/Tables/OrderTable'
import { getAllOrder } from '../../services/lib/orderHandler'
import { getAllUser } from '../../services/lib/userHandler'

const Order = ({ orders, users }) => {

    const [orderState, setOrderState] = useState(orders)

    return (
        <div className="min-h-screen w-full">
            <Head>
                <title>addidas Official Website India</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <Navbar />

            <main className="flex flex-col justify-center items-center mt-32">
                <div className='w-10/12'>
                    <Header />

                    <h1 className='font-bold text-xl my-4'>Users</h1>

                    <OrderTable orders={orderState} setOrderState={setOrderState} users={users}
                    />
                </div>
            </main>
        </div>
    )
}

export default Order

export async function getServerSideProps() {

    let orders = [];
    let users = [];

    try {
        const res = await getAllOrder();
        const res2 = await getAllUser();
        users = res2.data.users;
        if (res.data.success) {
            orders = res.data.orders;
        } else {
            orders = [];
        }
    } catch (err) {
        console.log(err.response.data)
    }

    return {
        props: { orders, users }
    }
}