import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'
import { AiOutlineShoppingCart } from 'react-icons/ai';
import ActivityCard from '../components/Cards/ActivityCard'
import PopluarProdutsCard from '../components/Cards/PopluarProdutsCard'
import Header from '../components/Layout/Header'
import Navbar from '../components/Layout/Navbar'
import { GetAllOrders, GetStats } from '../services/api';

const Dashboard = ({ stats }) => {

    const { user } = useSelector(state => state.auth)
    const [loading, setLoading] = useState(false)
    const [response, setResponse] = useState()

    useEffect(() => {
        const fetchData = async () => {
            setLoading(true)
            try {
                const { data } = await GetStats()
                setResponse(data)
                setLoading(false)
            } catch (err) {
                console.log(err)
                setLoading(false)
            }
        }
        fetchData()
    }, [])

    return (
        <div className="min-h-screen w-full">
            <Head>
                <title>addidas Official Website India</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <Navbar />

            <main className="flex flex-col w-full h-full justify-center items-center mt-32">
                <div className='w-11/12'>
                    <Header />
                    <div className='flex'>
                        <div className='w-9/12  p-4'>
                            <h1 className='font-bold text-xl my-4'>Overview</h1>

                            <div className='flex justify-between mt-4'>

                                <div className='border-2  w-full p-4'>
                                    <div className='flex justify-between mb-2 font-bold items-center'>
                                        <AiOutlineShoppingCart className='text-2xl' />
                                        <h1 className='text-green-500 text-xl'>+24%</h1>
                                    </div>
                                    <h1 className='font-bold text-2xl'>₹{response?.totalSales}</h1>
                                    <h1 className='font-medium text-xs text-gray-400'>Total Sales <span className='italic'>(All time)</span></h1>
                                </div>

                                <div className='border-2  w-full mx-8 p-4'>
                                    <div className='flex justify-between mb-2 font-bold items-center'>
                                        <i className="fas fa-users text-2xl"></i>
                                        <h1 className='text-green-500 text-xl'>+24%</h1>
                                    </div>
                                    <h1 className='font-bold text-2xl'>{response?.totalUsers}</h1>
                                    <h1 className='font-medium text-xs text-gray-400'>Total Users <span className='italic'>(All time)</span></h1>
                                </div>

                                <div className='border-2  w-full p-4'>
                                    <div className='flex justify-between mb-2 font-bold items-center'>
                                        <i className="fas fa-shopping-cart text-2xl"></i>
                                        <h1 className='text-green-500 text-xl'>+124%</h1>
                                    </div>
                                    <h1 className='font-bold text-2xl'>{response?.totalOrders}</h1>
                                    <h1 className='font-medium text-xs text-gray-400'>Total Orders <span className='italic'>(All time)</span></h1>
                                </div>

                            </div>

                            <div className='mt-8'>
                                <h1 className='font-bold text-xl'>Store Details</h1>

                                <div className='my-4 flex flex-col gap-4'>
                                    <h1 className='p-4 border px-4 text-xl'>2540 Orders are ready to be fulfill</h1>
                                    <h1 className='p-4 border px-4 text-xl'>492 Payments are to be capture</h1>
                                    <h1 className='p-4 border px-4 text-xl'>No Products are out of stock</h1>
                                </div>
                            </div>

                        </div>

                        <div className='w-3/12 p-4'>
                            <h1 className='font-bold text-xl my-4'>Activity</h1>
                            <div className='border-2  h-750 p-4 overflow-scroll'>
                                {
                                    response?.notifications.map((e) => <ActivityCard key={e._id} data={e} />)
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Dashboard