import Head from 'next/head'
import React, { useEffect } from 'react'
import { useSelector } from 'react-redux'
import ActivityCard from '../components/Cards/ActivityCard'
import PopluarProdutsCard from '../components/Cards/PopluarProdutsCard'
import Header from '../components/Layout/Header'
import Navbar from '../components/Layout/Navbar'

const Dashboard = () => {

    const userData = useSelector(state => state.user.currentUser)

    const user = userData ? userData.user : ""

    return (
        <div className="min-h-screen w-full">
            <Head>
                <title>addidas Official Website India</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <Navbar />

            <main className="flex flex-col w-full h-full justify-center items-center mt-32">
                <div className='w-11/12'>
                    <Header />
                    <div className='flex'>
                        <div className='w-9/12  p-4'>
                            <h1 className='font-bold text-xl my-4'>Overview</h1>

                            <div className='flex justify-between mt-4'>

                                <div className='border-2 border-black w-full p-4'>
                                    <div className='flex justify-between mb-2 font-bold items-center'>
                                        <i className="fas fa-shopping-bag text-2xl"></i>
                                        <h1 className='text-green-500 text-xl'>+24%</h1>
                                    </div>
                                    <h1 className='font-bold text-2xl'>$2400.00</h1>
                                    <h1 className='font-medium text-xs text-gray-400'>Total Sales</h1>
                                </div>

                                <div className='border-2 border-black w-full mx-8 p-4'>
                                    <div className='flex justify-between mb-2 font-bold items-center'>
                                        <i className="fas fa-users text-2xl"></i>
                                        <h1 className='text-green-500 text-xl'>+24%</h1>
                                    </div>
                                    <h1 className='font-bold text-2xl'>12.00</h1>
                                    <h1 className='font-medium text-xs text-gray-400'>Total Users</h1>
                                </div>

                                <div className='border-2 border-black w-full p-4'>
                                    <div className='flex justify-between mb-2 font-bold items-center'>
                                        <i className="fas fa-shopping-cart text-2xl"></i>
                                        <h1 className='text-green-500 text-xl'>+124%</h1>
                                    </div>
                                    <h1 className='font-bold text-2xl'>112,400.00</h1>
                                    <h1 className='font-medium text-xs text-gray-400'>Total Orders</h1>
                                </div>

                            </div>

                            <div className='mt-8'>
                                <h1 className='font-bold text-xl'>Popular Products</h1>

                                <div className='my-4'>
                                    <PopluarProdutsCard />
                                    <PopluarProdutsCard />
                                    <PopluarProdutsCard />
                                </div>
                            </div>

                        </div>

                        <div className='w-3/12 p-4'>
                            <h1 className='font-bold text-xl my-4'>Activity</h1>
                            <div className='border-2 border-black h-750 p-4 overflow-scroll'>
                                <ActivityCard />
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Dashboard

