import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import Header from '../components/Layout/Header'
import Navbar from '../components/Layout/Navbar'
import UserTable from '../components/Tables/UserTable'
import { GetAllUsers } from '../services/api'

const Users = () => {

    const [usersState, setUsersState] = useState();

    useEffect(() => {

        const fetchData = async () => {
            try {
                const { data } = await GetAllUsers();
                setUsersState(data.users)
            } catch (err) {
                console.log(err)
            }

        }

        fetchData()

    }, [])

    return (
        <div className="min-h-screen w-full">
            <Head>
                <title>addidas Official Website India</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <Navbar />

            <main className="flex flex-col justify-center items-center mt-32">

                <div className='w-10/12'>
                    <Header />

                    <h1 className='font-bold text-xl my-4'>Users</h1>

                    <UserTable users={usersState} setUsersState={setUsersState} />
                </div>
            </main>
        </div>
    )
}

export default Users